version: "3.11"

# It can also be run from docker-compose by specifying the following options.
# Note that only the current directory can be specified as a target.
# 
# $ ARGUMENTS="'/$MFT' ./path/to/imagefile" docker-compose up

services:
  app:
    container_name: ntfsdump
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - ARGUMENTS="-h"
    command: ${ARGUMENTS}