name: build-docker-image

on:
  push:
    branches:
      - master
      - 'feature/*'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build --tag ghcr.io/$GITHUB_ACTOR/ntfsdump:latest \
          --tag ghcr.io/$GITHUB_ACTOR/ntfsdump:$(echo $GITHUB_SHA | head -c7) \
          .

      - name: Publish Docker Image
        run: |
          docker push ghcr.io/$GITHUB_ACTOR/ntfsdump:latest
          docker push ghcr.io/$GITHUB_ACTOR/ntfsdump:$(echo $GITHUB_SHA | head -c7)
